default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres #Your postgres username
  password: postgres #Your postgres password
  pool: 5
  host: localhost
  timeout: 5000

development:
  <<: *default
  database: race_management

test:
  <<: *default
  database: race_management_test


production:
  primary:
    <<: *default
    database: race_management_production
